imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ["en"] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# app/config/config.yml
easy_admin:
    site_name: "Alea"
    design:
        form_theme: 'vertical'
        brand_color: '#2980b9'
        color_scheme: 'light'
        assets:
            favicon: '/assets/backend/favicon.png'
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:

        #TABLE PLAYER ['id', 'name', 'idTeam','teams']
        Player:
            class: AppBundle\Entity\Player
            label: 'Player'
            list: 
                title: '%%entity_label%% listing'
                fields: ['name', 'teams']
            new:
                fields: 
                    - { property: 'name', icon: 'user' }
            form: 
                fields: 
                    - { type: 'section', label: 'Player Details' }
                    - { property: 'name', icon: 'user' }
                    - { property: 'teams', type_options: { required: false } }
            edit:
                fields: 
                    - { property: 'name', icon: 'customer' }
                    - { property: 'teams', type_options: { required: false } }
            help: 'Add your data'
            show: # 'help' is not defined, so the global help message is displayed
                # ...
                max_results: 30
            search:
                # use the null value to not display the inherited global help message
                help: null

        #TABLE TEAM ['id', 'name']
        Team: 
            class: AppBundle\Entity\Team
            label: 'Team'
            list: 
                title: '%%entity_label%% listing'
                help: 'List of Team table'
                fields: 
                    - { property: 'name', icon: 'users' }
                    - { property: 'players', type: 'array' }
            form:
                fields:
                    - { property: 'name', icon: 'users' }
                    - { property: 'players', label: 'Players :', type_options: { required: false }}

        #TABLE TEAM_HAS_PLAYERS ['id', 'idPlayer', 'idTeam', 'DateStart', 'DateEnd']
        #Team_Has_Players:
        #    class: AppBundle\Entity\Team_Has_Players
        Article:
            class: AppBundle\Entity\Article